export const ar = {
  app: {
    title: 'منصة تعلم Linux/Kali',
    subtitle: 'تعلم الأوامر، الاختبارات، والبيئة المحاكاة.',
    headerTitle: 'منصة تعلم Linux/Kali',
    headerSubtitle: 'التعلم التفاعلي مع Linux/Kali',
    language: 'English',
    languageSwitch: 'English',
    nightMode: 'الوضع الليلي',
    dayMode: 'الوضع النهاري',
    phaseLabel: '📚 المرحلة:',
    reset: 'إعادة ضبط النظام',
    resetFull: 'إعادة ضبط كامل',
    startPhaseTest: 'اختبار المرحلة',
    phaseProgressLabel: '📊 تقدم المرحلة:',
    phaseStatsPrefix: 'أتقنت',
    phaseStatsOf: 'من',
    phaseStatsSuffix: 'أمر',
    midtermTest: 'اختبار نصفي',
    finalTest: 'اختبار نهائي',
    submitTest: 'إرسال الإجابات',
    closeTest: 'إغلاق',
    execute: 'تنفيذ',
    hint: 'تلميح',
    openTerminal: 'فتح الطرفية',
    close: 'إغلاق',
    stats: '📊 الإحصائيات',
    statsTitle: 'لوحة الإحصائيات',
    achievements: '🏆 الإنجازات',
    level: 'المستوى',
    testsCompleted: 'الاختبارات المكتملة',
    bestStreak: 'أفضل سلسلة',
    trainingTime: 'وقت التدريب',
    commandsLearned: 'الأوامر المكتسبة',
    phaseProgress: 'تقدم المرحلة',
    commandRequired: 'نفّذ الأمر التالي في الطرفية:',
    mission: 'مهمة',
    usage: 'الاستخدام',
    try: 'جرّب',
    mastered: 'مكتسب',
    masterIt: 'أتقنت؟',
    confirmReset: 'هل تريد إعادة ضبط نظام الملفات الافتراضي؟',
    confirmResetFull: 'هل تريد إعادة ضبط النظام بالكامل؟ سيتم حذف جميع البيانات والإنجازات والإحصائيات. هذا الإجراء لا يمكن التراجع عنه.',
    resetDone: 'تمت إعادة الضبط.',
    resetFullDone: 'تمت إعادة الضبط الكامل.',
    correctCommand: '✅ أمر صحيح!',
    wrongCommand: '❌ أمر خاطئ.',
    hintText: '💡 اكتب الأمر كما هو مطلوب.',
    practicalPassed: '✅ اجتزت الجزء العملي!',
    practicalFailed: '❌ لم تجتز الجزء العملي.',
    theory: 'نظري',
    practical: 'عملي',
    executeCommand: 'نفّذ الأمر: {cmd}',
    noQuestions: 'لا توجد أسئلة كافية لهذه المرحلة.',
    noStats: 'لا توجد إحصائيات بعد، قم بإجراء اختباراتك الأولى.',
    viewStats: 'عرض الإحصائيات',
    manTitle: 'دليل الأمر {cmd}',
    manSyntax: 'الصيغة: {syntax}',
    manDesc: 'الوصف: {desc}',
    manOptions: 'الخيارات:',
    manExamples: 'أمثلة:',
    noMan: 'لا توجد معلومات إضافية لهذا الأمر.',
    achievementUnlocked: '🎉 إنجاز جديد: {name} (+{xp} XP)',
    practicalProgress: 'تقدم العملي: {solved} من {total}',
    totalTests: 'عدد الاختبارات',
    avgScore: 'متوسط الدرجات',
    phasesMastered: 'المراحل المتقنة',
    bestStreakLabel: 'أفضل سلسلة نجاح',
    trainingTimeLabel: 'وقت التدريب',
    phaseProgressStats: 'تقدم المراحل',
    question: 'السؤال',
    of: 'من',
    chooseOption: 'اختر الإجابة الصحيحة:',
    correctAnswer: 'الإجابة الصحيحة:',
    testComplete: 'اكتمل الاختبار!',
    phaseTestTitle: 'اختبار المرحلة {phase}',
    midtermTestTitle: 'اختبار نصفي شامل',
    finalTestTitle: 'اختبار نهائي شامل',
    result: 'النتيجة',
    testPassed: '✅ نجحت! +{xp} XP',
    testFailed: '❌ لم تنجح. حاول مجدداً.',
    placeholder: 'اكتب الأمر...',
    prompt: 'kali@kali:~$',
    languageLabel: 'اللغة',
    currentLanguage: 'العربية',
    terminalTitle: 'الطرفية',
    helpTitle: 'دليل الأمر',
    toolTipHelp: 'عرض المساعدة',
    toolTipOpenTerminal: 'فتح الطرفية',
    toolTipToggleLanguage: 'تبديل اللغة',
    toolTipToggleTheme: 'تبديل الوضع الليلي',
    toolTipStats: 'عرض الإحصائيات',
    open: 'فتح',
    show: 'عرض',
    value: 'القيمة',
    progress: 'التقدم',
    xp: 'XP',
    answerPlaceholder: 'اكتب الأمر هنا',
    stageLabel: 'المرحلة',
    command: 'الأمر',
    description: 'الوصف',
    syntax: 'الصيغة',
    examples: 'الأمثلة',
    options: 'الخيارات',
    noData: 'لا توجد بيانات',
    toggleLanguage: 'English'
  },
  terminal: {
    title: 'الطرفية',
    execute: 'تنفيذ',
    clear: 'مسح',
    hint: 'تلميح',
    placeholder: 'اكتب الأمر...'
  },
  tests: {
    phase: 'اختبار المرحلة',
    midterm: 'اختبار نصفي',
    final: 'اختبار نهائي',
    submit: 'إرسال الإجابات',
    close: 'إغلاق',
    question: 'السؤال',
    of: 'من',
    choose: 'اختر الإجابة الصحيحة',
    result: 'النتيجة',
    success: 'نجاح',
    failure: 'فشل',
    score: 'الدرجة',
    xp: 'XP'
  },
  messages: {
    success: '✅ تم بنجاح',
    error: '❌ حدث خطأ',
    commandExecuted: '✅ تم تنفيذ الأمر بنجاح',
    resetVfs: 'تمت إعادة ضبط VFS فقط.',
    resetFull: 'تمت إعادة الضبط الكامل.',
    examSubmitted: 'تم إرسال الإجابات بنجاح.'
  },
  header: {
    title: 'منصة تعلم Linux/Kali',
    subtitle: 'التعلم التفاعلي مع Linux/Kali'
  },
  language: {
    switch: 'English',
    label: 'اللغة',
    current: 'العربية'
  },
  commands: {
    less: { desc: 'عرض ملف بالتدريج', usage: 'لقراءة ملفات طويلة بصفحات.', syntax: 'less [file]', options: [], examples: ['less file.txt'] },
    more: { desc: 'عرض ملف بالتدريج (أقدم)', usage: 'مشابه لـ less لكن أقدم.', syntax: 'more [file]', options: [], examples: ['more file.txt'] }
  }
};