export const en = {
  app: {
    title: 'Linux/Kali Learning Platform',
    subtitle: 'Learn commands, tests, and the simulated environment.',
    headerTitle: 'Linux/Kali Learning Platform',
    headerSubtitle: 'Interactive learning with Linux/Kali',
    language: 'العربية',
    languageSwitch: 'العربية',
    nightMode: 'Night Mode',
    dayMode: 'Day Mode',
    phaseLabel: '📚 Phase:',
    reset: 'Reset System',
    resetFull: 'Full Reset',
    startPhaseTest: 'Phase Test',
    phaseProgressLabel: '📊 Phase Progress:',
    phaseStatsPrefix: 'Mastered',
    phaseStatsOf: 'of',
    phaseStatsSuffix: 'commands',
    midtermTest: 'Midterm Test',
    finalTest: 'Final Test',
    submitTest: 'Submit Answers',
    closeTest: 'Close',
    execute: 'Execute',
    hint: 'Hint',
    openTerminal: 'Open Terminal',
    close: 'Close',
    stats: '📊 Statistics',
    statsTitle: 'Statistics Panel',
    achievements: '🏆 Achievements',
    level: 'Level',
    testsCompleted: 'Completed Tests',
    bestStreak: 'Best Streak',
    trainingTime: 'Training Time',
    commandsLearned: 'Commands Learned',
    phaseProgress: 'Phase Progress',
    commandRequired: 'Execute the following command in the terminal:',
    mission: 'Mission',
    usage: 'Usage',
    try: 'Try',
    mastered: 'Mastered',
    masterIt: 'Mastered?',
    confirmReset: 'Do you want to reset the virtual file system?',
    confirmResetFull: 'Do you want to fully reset the system? All data, achievements, and statistics will be deleted. This action is irreversible.',
    resetDone: 'Reset done.',
    resetFullDone: 'Full reset done.',
    correctCommand: '✅ Correct command!',
    wrongCommand: '❌ Wrong command.',
    hintText: '💡 Type the command as required.',
    practicalPassed: '✅ You passed the practical part!',
    practicalFailed: '❌ You failed the practical part.',
    theory: 'Theory',
    practical: 'Practical',
    executeCommand: 'Execute command: {cmd}',
    noQuestions: 'Not enough questions for this phase.',
    noStats: 'No statistics yet, take your first tests.',
    viewStats: 'View Statistics',
    manTitle: 'Manual for {cmd}',
    manSyntax: 'Syntax: {syntax}',
    manDesc: 'Description: {desc}',
    manOptions: 'Options:',
    manExamples: 'Examples:',
    noMan: 'No additional information for this command.',
    achievementUnlocked: '🎉 New achievement: {name} (+{xp} XP)',
    practicalProgress: 'Practical progress: {solved} of {total}',
    totalTests: 'Total Tests',
    avgScore: 'Average Score',
    phasesMastered: 'Phases Mastered',
    bestStreakLabel: 'Best streak',
    trainingTimeLabel: 'Training time',
    phaseProgressStats: 'Phase progress',
    question: 'Question',
    of: 'of',
    chooseOption: 'Choose the correct answer:',
    correctAnswer: 'Correct answer:',
    testComplete: 'Test completed!',
    phaseTestTitle: 'Phase {phase} Test',
    midtermTestTitle: 'Comprehensive Midterm Test',
    finalTestTitle: 'Comprehensive Final Test',
    result: 'Result',
    testPassed: '✅ Passed! +{xp} XP',
    testFailed: '❌ Failed. Try again.',
    placeholder: 'Type a command...',
    prompt: 'kali@kali:~$',
    languageLabel: 'Language',
    currentLanguage: 'English',
    terminalTitle: 'Terminal',
    helpTitle: 'Command Guide',
    toolTipHelp: 'Show help',
    toolTipOpenTerminal: 'Open terminal',
    toolTipToggleLanguage: 'Toggle language',
    toolTipToggleTheme: 'Toggle dark mode',
    toolTipStats: 'Show statistics',
    open: 'Open',
    show: 'Show',
    value: 'Value',
    progress: 'Progress',
    xp: 'XP',
    answerPlaceholder: 'Type the command here',
    stageLabel: 'Stage',
    command: 'Command',
    description: 'Description',
    syntax: 'Syntax',
    examples: 'Examples',
    options: 'Options',
    noData: 'No data',
    toggleLanguage: 'العربية'
  },
  terminal: {
    title: 'Terminal',
    execute: 'Execute',
    clear: 'Clear',
    hint: 'Hint',
    placeholder: 'Type a command...'
  },
  tests: {
    phase: 'Phase Test',
    midterm: 'Midterm',
    final: 'Final Test',
    submit: 'Submit Answers',
    close: 'Close',
    question: 'Question',
    of: 'of',
    choose: 'Choose the correct answer',
    result: 'Result',
    success: 'Success',
    failure: 'Failure',
    score: 'Score',
    xp: 'XP'
  },
  messages: {
    success: '✅ Done successfully',
    error: '❌ An error occurred',
    commandExecuted: '✅ Command executed successfully',
    resetVfs: 'The VFS was reset.',
    resetFull: 'The system was fully reset.',
    examSubmitted: 'Answers submitted successfully.'
  },
  header: {
    title: 'Linux/Kali Learning Platform',
    subtitle: 'Interactive learning with Linux/Kali'
  },
  language: {
    switch: 'العربية',
    label: 'Language',
    current: 'English'
  },
  commands: {
    less: { desc: 'View file paginated', usage: 'Read long files page by page.', syntax: 'less [file]', options: [], examples: ['less file.txt'] },
    more: { desc: 'View file paginated (older)', usage: 'Similar to less but older.', syntax: 'more [file]', options: [], examples: ['more file.txt'] }
  }
};